# Site settings
title: Rodrigo Rivera - Machine Learning Research
description: International by design and accident, speaking 5 languages, Rodrigo has worked on technical leadership roles in machine learning research and data science in South East Asia, the Americas and Eastern and Western Europe with leading FMCG and Internet companies over the last 10 years. A data science head and founder of Emplido, an analytics company acquired by Experteer Inc. He has been an invited speaker at the Google Developer Day and the BMWi as well as conducted research with the World Bank and the Mexican federal government on anti-kidnapping technologies.
# baseurl: "/particle" # the subpath of your site, e.g. /blog
url: "http://rodrigo-rivera.com" # the base hostname & protocol for your site e.g. http://willianjusten.com.br

# User settings
username: Rodrigo Rivera
user_description: <p>International by design and accident, speaking 5 languages, Rodrigo has worked on technical leadership roles in machine learning research and data science in South East Asia, the Americas and Eastern and Western Europe with leading FMCG and Internet companies over the last 10 years.</p><br/><p>A data science head and founder of Emplido, an analytics company acquired by Experteer Inc. He has been an invited speaker at the Google Developer Day and the BMWi as well as conducted research with the World Bank and the Mexican federal government on anti-kidnapping technologies.</p>
user_title: Data Science & Machine Learning Lead
email: rodrigo.riveracastro@skoltech.ru
twitter_username: rorcde
github_username:  rodrigorivera
linkedin_username:  riverarodrigo

# Google-analytics
google-analytics:
  id: ""

exclude: ['package.json', 'src' , 'node_modules']
