# Site settings
title: Rodrigo Rivera - Machine Learning and Data Science
description: Rodrigo leads data science teams. With a strong commercial focus and a solid background in machine learning, he specialises in personalisation, optimization, demand planning & crm for the consumer goods and Internet industries.A German entrepreneur and founder of Emplido, an analytics recruiting company acquired by Experteer Inc. He has been an invited speaker at the Google Developer Day and the BMWi as well as conducted research with the World Bank and the Mexican federal government on anti-kidnapping technologies. Internationally educated, he graduated with a CEMS Masters in International Management from NUS, VŠE and Bocconi, a Big Data Systems degree from HSE, a Computer Science degree from the TU München and a Technology Management honors graduate degree from CDTM, a top 10 percent of the class elite joint institute. He is fluent in four languages and has lived and worked in 14 countries in the Americas, Europe and Asia.
# baseurl: "/particle" # the subpath of your site, e.g. /blog
url: "http://rodrigo-rivera.com" # the base hostname & protocol for your site e.g. http://willianjusten.com.br

# User settings
username: Rodrigo Rivera
user_description: Bicycle rights irony actually neutra typewriter lyft. Man bun taxidermy put a bird on it, umami yr ramps pop-up ugh bushwick chia lo-fi. Occupy bitters pour-over snackwave you probably haven't heard of them small batch. Cornhole mustache man bun letterpress echo park VHS.
user_title: Data Science & Machine Learning Lead
email: rorcde@gmail.com
twitter_username: roriveca
github_username:  rodrigorivera
#gplus_username:  lorem_ipsum

# Google-analytics
google-analytics:
  id: ""

exclude: ['package.json', 'src' , 'node_modules']
